[project]
authors = ["Scott Henderson <scottyhq@gmail.com>"]
channels = ["conda-forge"]
name = "accelerator2025"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
xarray = ">=2025.1.2,<2026"
ipykernel = ">=6.29.5,<7"
flox = ">=0.10.0,<0.11"
numbagg = ">=0.9.0,<0.10"
dask = ">=2025.2.0,<2026"
xoak = ">=0.1.1,<0.2"
virtualizarr = ">=1.3.0,<2"
zarr = ">=3.0.3,<4"
cartopy = ">=0.24.0,<0.25"
distributed = ">=2025.2.0,<2026"
setuptools = ">=75.8.0,<76"
h5netcdf = ">=1.5.0,<2"
cftime = ">=1.6.4,<2"
